some typos and fix a bug problem solution
azl397985856/leetcode pull request #543
Opened 2022-04-23 10:04 UTC by tianyu-su

2022-04-24 06:00 UTC, azl397985856 requested changes

2022-04-24 06:00 UTC, azl397985856 commented on thinkings/search.md
> +from sortedcontainers import SortedList
这个 bug 具体指什么？

2022-07-10 09:14 UTC, cherie-wuyajun commented
这是来自QQ邮箱的自动回复邮件。您好，邮件已收到，我将会尽快给您回复。

2022-07-10 09:15 UTC, fyyzkd commented
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

2022-07-10 09:15 UTC, xiaosisong commented
我已经收到了，会尽快查看的，谢谢

2022-09-21 17:09 UTC, azl397985856 approved these changes

2022-09-21 17:10 UTC, merged